import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArchiveRestore, BarChart3, BookOpen, Bot, Boxes, ChevronLeft,
  ChevronRight, CircleDollarSign, ClipboardList, CloudDownload, Database, FileSearch, FileText,
  Home, IndianRupee, LogIn, LogOut, Menu, Moon, NotebookPen, PackagePlus, PencilLine, Plus,
  ReceiptText, RefreshCw, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Sun, Trash2,
  TrendingUp, Upload, UserRound, UsersRound, WalletCards, X,
} from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { format, parseISO, differenceInDays } from 'date-fns'
import writeXlsxFile from 'write-excel-file'

const CATEGORIES = ['Sarees', 'Salwar Suits', 'Lehengas', 'Kurtis', 'Western Wear', 'Accessories', 'Kids Wear', 'Blouse', 'Fabric', 'Other']
const PAYMENT_METHODS = ['Cash', 'UPI', 'Card', 'Bank Transfer', 'Part Payment', 'Credit']
const COLORS = ['#2563eb', '#059669', '#d97706', '#7c3aed', '#dc2626', '#0ea5e9', '#8b5cf6']
const today = () => new Date().toISOString().slice(0, 10)
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`
const dateLabel = (value) => { try { return format(parseISO(String(value).slice(0, 10)), 'dd MMM yyyy') } catch { return value || '—' } }

const NAV = [
  ['dashboard', 'Overview', Home], ['add-sale', 'Add sale', Plus], ['review', 'Review accounts', ClipboardList],
  ['update', 'Update transaction', PencilLine], ['customers', 'Customers', UsersRound], ['vendors', 'Vendors', ShoppingBag],
  ['analytics', 'Analytics', BarChart3], ['reminders', 'Reminders', AlertTriangle], ['bill', 'Generate bill', ReceiptText],
  ['inventory', 'Inventory', Boxes], ['passbook', 'Passbook reader', FileSearch], ['notes', 'Work notes', NotebookPen],
  ['ai', 'AI assistant', Sparkles], ['technical', 'Technical', Database], ['security', 'Security & devices', ShieldCheck],
  ['backup', 'Backup & restore', ArchiveRestore],
]

async function request(path, options = {}) {
  const token = localStorage.getItem('boutique_token')
  const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...options.headers }
  if (token) headers.Authorization = `Bearer ${token}`
  const controller = new AbortController()
  const timeout = window.setTimeout(() => controller.abort(), options.timeout || 15000)
  let response
  try {
    response = await fetch(`/api${path}`, { ...options, headers, signal: controller.signal })
  } catch (error) {
    if (error.name === 'AbortError') throw new Error('The API did not respond. Make sure npm run dev is still running, then try again.')
    throw new Error('Cannot reach the boutique API. Start the app with npm run dev and try again.')
  } finally {
    window.clearTimeout(timeout)
  }
  if (response.status === 204) return null
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.error || 'Request failed.')
  return data
}

function Button({ children, variant = 'primary', icon: Icon, className = '', ...props }) {
  return <button className={`button ${variant} ${className}`} {...props}>{Icon && <Icon size={17} />}{children}</button>
}
function PageHead({ title, eyebrow, action }) {
  return <header className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{action}</header>
}
function Card({ children, className = '' }) { return <section className={`card ${className}`}>{children}</section> }
function Empty({ icon: Icon = ArchiveRestore, title = 'Nothing here yet', copy = 'New records will appear here.' }) {
  return <div className="empty"><span><Icon size={26} /></span><h3>{title}</h3><p>{copy}</p></div>
}
function Field({ label, as = 'input', children, ...props }) {
  const Tag = as
  return <label className="field"><span>{label}</span><Tag {...props}>{children}</Tag></label>
}
function Metric({ label, value, hint, icon: Icon, tone = 'blue' }) {
  return <Card className={`metric ${tone}`}><div className="metric-icon">{Icon && <Icon size={19} />}</div><div><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</div></Card>
}
function Status({ paid, delayed }) {
  if (delayed) return <span className="badge red">Delayed</span>
  return paid ? <span className="badge green">Received</span> : <span className="badge amber">Pending</span>
}
function Notice({ value, clear }) { return value ? <div className={`notice ${value.type || 'success'}`}>{value.text}<button onClick={clear}><X size={16} /></button></div> : null }

const blankSale = () => ({ customer_name: '', customer_phone: '', sale_date: today(), vendor: '', product_category: 'Sarees', product_description: '', buying_price: '', selling_price: '', amount_paid: '', payment_method: 'UPI', delay_status: false, notes: '' })

function SaleForm({ initial, onSave, publicMode = false, submitLabel = 'Save sale' }) {
  const [form, setForm] = useState(initial || blankSale())
  const [busy, setBusy] = useState(false)
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }))
  const pending = Math.max(0, Number(form.selling_price || 0) - Number(form.amount_paid || 0))
  async function submit(e) {
    e.preventDefault(); setBusy(true)
    try { await onSave(form); if (!initial) setForm(blankSale()) } finally { setBusy(false) }
  }
  return <form onSubmit={submit} className="sale-form">
    <div className="form-section"><div className="section-title"><UserRound size={18} /><div><h3>Customer</h3><p>Contact and transaction date</p></div></div>
      <div className="form-grid three"><Field label="Customer name" value={form.customer_name} onChange={(e) => set('customer_name', e.target.value)} required /><Field label="Phone number" value={form.customer_phone} onChange={(e) => set('customer_phone', e.target.value)} /><Field label="Sale date" type="date" value={form.sale_date} onChange={(e) => set('sale_date', e.target.value)} required /></div>
    </div>
    <div className="form-section"><div className="section-title"><ShoppingBag size={18} /><div><h3>Item details</h3><p>Product, category and sourcing</p></div></div>
      <div className="form-grid three"><Field label="Category" as="select" value={form.product_category} onChange={(e) => set('product_category', e.target.value)}>{CATEGORIES.map((x) => <option key={x}>{x}</option>)}</Field><Field label="Vendor" value={form.vendor} onChange={(e) => set('vendor', e.target.value)} /><Field label="Description" value={form.product_description} onChange={(e) => set('product_description', e.target.value)} /></div>
    </div>
    <div className="form-section"><div className="section-title"><IndianRupee size={18} /><div><h3>Payment</h3><p>Pricing and collection status</p></div></div>
      <div className="form-grid four"><Field label="Buying price" type="number" min="0" step="0.01" value={form.buying_price} onChange={(e) => set('buying_price', e.target.value)} /><Field label="Selling price" type="number" min="0" step="0.01" value={form.selling_price} onChange={(e) => set('selling_price', e.target.value)} required /><Field label="Amount paid" type="number" min="0" step="0.01" value={form.amount_paid} onChange={(e) => set('amount_paid', e.target.value)} /><Field label="Method" as="select" value={form.payment_method} onChange={(e) => set('payment_method', e.target.value)}>{PAYMENT_METHODS.map((x) => <option key={x}>{x}</option>)}</Field></div>
      <div className="amount-preview"><span>Pending after this sale</span><strong>{money(pending)}</strong></div>
    </div>
    <Field label="Notes" as="textarea" rows="3" value={form.notes} onChange={(e) => set('notes', e.target.value)} placeholder="Alterations, delivery details, colour, size…" />
    <div className="form-actions">{publicMode && <p>No sign-in needed. The boutique team can review this entry.</p>}<Button type="submit" icon={busy ? RefreshCw : Plus} disabled={busy}>{busy ? 'Saving…' : submitLabel}</Button></div>
  </form>
}

function PublicHome({ onLogin }) {
  const [loginOpen, setLoginOpen] = useState(false), [notice, setNotice] = useState(null)
  async function addSale(form) { try { await request('/public/sales', { method: 'POST', body: JSON.stringify(form) }); setNotice({ text: 'Sale submitted successfully.' }) } catch (e) { setNotice({ type: 'error', text: e.message }); throw e } }
  return <main className="public-page">
    <header className="public-nav"><div className="brand-lockup"><img src="/krishna_symbol.png" onError={(e) => { e.currentTarget.style.display = 'none' }} /><div><strong>Shree Krishna</strong><span>Boutique manager</span></div></div><Button variant="ghost" icon={LogIn} onClick={() => setLoginOpen(true)}>Admin sign in</Button></header>
    <div className="public-wrap"><section className="hero"><span className="eyebrow">Shree Krishna Boutique</span><h1>Beautifully simple<br /><em>sale entry.</em></h1><p>Record customer purchases and payment details. Your entry is saved securely for the boutique team.</p><div className="hero-pills"><span>Private & secure</span><span>Instant confirmation</span><span>Mobile friendly</span></div></section><Card className="public-form"><div className="card-heading"><span className="icon-box"><ShoppingBag /></span><div><h2>New sale</h2><p>Enter the purchase details below</p></div></div><Notice value={notice} clear={() => setNotice(null)} /><SaleForm publicMode onSave={addSale} /></Card></div>
    {loginOpen && <LoginModal close={() => setLoginOpen(false)} onLogin={onLogin} />}
  </main>
}

function LoginModal({ close, onLogin }) {
  const [form, setForm] = useState({ username: 'admin', password: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/auth/login', { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('boutique_token', data.token); localStorage.setItem('boutique_user', JSON.stringify(data.user)); onLogin(data.user) } catch (e) { setError(e.message) } finally { setBusy(false) } }
  return <div className="modal-backdrop" onMouseDown={close}><div className="modal login-modal" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={close}><X /></button><span className="login-mark"><ShieldCheck /></span><span className="eyebrow">Protected workspace</span><h2>Welcome back</h2><p>Sign in to manage boutique accounts.</p><form onSubmit={submit}><Field label="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /><Field label="Password" type="password" autoFocus value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} />{error && <p className="form-error">{error}</p>}<Button type="submit" disabled={busy} icon={LogIn}>{busy ? 'Signing in…' : 'Sign in'}</Button></form><small>Uses the credentials configured in .env or credentials/.env.</small></div></div>
}

function Shell({ user, logout }) {
  const [page, setPage] = useState('dashboard'), [mobile, setMobile] = useState(false), [collapsed, setCollapsed] = useState(false)
  const [theme, setTheme] = useState(localStorage.getItem('boutique_theme') || 'light')
  const [sales, setSales] = useState([]), [inventory, setInventory] = useState([]), [notes, setNotes] = useState([]), [loading, setLoading] = useState(true), [notice, setNotice] = useState(null)
  const reload = useCallback(async () => { setLoading(true); try { const [s, i, n] = await Promise.all([request('/sales'), request('/inventory'), request('/notes')]); setSales(s); setInventory(i); setNotes(n) } catch (e) { setNotice({ type: 'error', text: e.message }) } finally { setLoading(false) } }, [])
  useEffect(() => { reload() }, [reload])
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('boutique_theme', theme) }, [theme])
  function navigate(id) { setPage(id); setMobile(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const context = { sales, inventory, notes, reload, notice: setNotice, loading }
  const pages = { dashboard: <Dashboard {...context} go={navigate} />, 'add-sale': <AddSale {...context} />, review: <Review {...context} />, update: <UpdateSale {...context} />, customers: <Customers {...context} />, vendors: <Vendors {...context} />, analytics: <Analytics {...context} />, reminders: <Reminders {...context} />, bill: <Billing {...context} />, inventory: <Inventory {...context} />, passbook: <Passbook {...context} />, notes: <Notes {...context} />, ai: <AI />, technical: <Technical {...context} />, security: <Security />, backup: <Backup {...context} /> }
  return <div className={`app-shell ${collapsed ? 'is-collapsed' : ''}`}>
    <aside className={`sidebar ${mobile ? 'mobile-open' : ''}`}><div className="sidebar-top"><div className="brand-lockup"><img src="/krishna_symbol.png" onError={(e) => { e.currentTarget.style.display = 'none' }} /><div><strong>Shree Krishna</strong><span>Boutique manager</span></div></div><button className="mobile-close" onClick={() => setMobile(false)}><X /></button></div><nav>{NAV.map(([id, label, Icon]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => navigate(id)} title={label}><Icon size={18} /><span>{label}</span></button>)}</nav><div className="sidebar-foot"><div className="user-chip"><span>{user.username.slice(0, 1).toUpperCase()}</span><div><strong>{user.username}</strong><small>Administrator</small></div></div><button className="nav-logout" onClick={logout}><LogOut size={18} /><span>Sign out</span></button></div></aside>
    <div className="main-area"><header className="topbar"><div><button className="mobile-menu" onClick={() => setMobile(true)}><Menu /></button><button className="collapse" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <ChevronRight /> : <ChevronLeft />}</button><div className="breadcrumb"><span>Workspace</span><strong>{NAV.find(([id]) => id === page)?.[1]}</strong></div></div><div><button className="icon-button" onClick={reload} title="Refresh data"><RefreshCw size={18} /></button><button className="icon-button" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} title="Toggle theme">{theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}</button><button className="icon-button" onClick={() => navigate('technical')} title="Settings"><Settings size={18} /></button></div></header><main className="content"><Notice value={notice} clear={() => setNotice(null)} />{loading && <div className="loading-bar" />}{pages[page]}</main></div>
  </div>
}

function calcMetrics(sales) {
  const revenue = sales.reduce((n, x) => n + Number(x.selling_price || 0), 0), buying = sales.reduce((n, x) => n + Number(x.buying_price || 0), 0), pending = sales.reduce((n, x) => n + Number(x.pending_amount || 0), 0)
  return { count: sales.length, revenue, profit: revenue - buying, pending, customers: new Set(sales.map((x) => x.customer_name)).size }
}
function monthlyData(sales) { const map = {}; sales.forEach((x) => { const key = String(x.sale_date || '').slice(0, 7); if (!key) return; map[key] ||= { month: key, revenue: 0, profit: 0 }; map[key].revenue += Number(x.selling_price || 0); map[key].profit += Number(x.selling_price || 0) - Number(x.buying_price || 0) }); return Object.values(map).sort((a, b) => a.month.localeCompare(b.month)).slice(-8).map((x) => ({ ...x, month: x.month.slice(5) + '/' + x.month.slice(2, 4) })) }

function Dashboard({ sales, go }) {
  const m = calcMetrics(sales), monthly = monthlyData(sales), recent = sales.slice(0, 7)
  return <><PageHead eyebrow="Business snapshot" title="Good to see you." action={<Button icon={Plus} onClick={() => go('add-sale')}>New sale</Button>} /><div className="metrics-grid"><Metric label="Total revenue" value={money(m.revenue)} hint={`${m.count} transactions`} icon={IndianRupee} /><Metric label="Gross profit" value={money(m.profit)} hint={`${m.revenue ? ((m.profit / m.revenue) * 100).toFixed(1) : 0}% margin`} icon={TrendingUp} tone="green" /><Metric label="Pending" value={money(m.pending)} hint="Needs collection" icon={WalletCards} tone="amber" /><Metric label="Customers" value={m.customers} hint="Unique customers" icon={UsersRound} tone="violet" /></div><div className="dashboard-grid"><Card className="chart-card"><div className="card-title"><div><h2>Revenue overview</h2><p>Revenue and gross profit by month</p></div><span className="badge blue">Last 8 months</span></div>{monthly.length ? <ResponsiveContainer width="100%" height={300}><AreaChart data={monthly}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.3}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)" /><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={(v) => `₹${v/1000}k`}/><Tooltip formatter={(v) => money(v)} /><Area type="monotone" dataKey="revenue" stroke="#2563eb" strokeWidth={3} fill="url(#revenue)"/><Line type="monotone" dataKey="profit" stroke="#059669" /></AreaChart></ResponsiveContainer> : <Empty icon={BarChart3} title="No chart data" copy="Add your first sale to start the revenue trend." />}</Card><Card className="quick-card"><div className="card-title"><div><h2>Quick actions</h2><p>Common daily tasks</p></div></div>{[['Record a sale','Create a customer transaction',Plus,'add-sale'],['Collect payment','Review pending accounts',CircleDollarSign,'review'],['Create a bill','Generate a customer invoice',ReceiptText,'bill'],['Add work note','Log today’s bookkeeping',NotebookPen,'notes']].map(([title,copy,Icon,id]) => <button key={id} onClick={() => go(id)}><span><Icon /></span><div><strong>{title}</strong><small>{copy}</small></div><ChevronRight /></button>)}</Card></div><Card className="table-card"><div className="card-title"><div><h2>Recent transactions</h2><p>Latest boutique activity</p></div><Button variant="ghost" onClick={() => go('review')}>View all</Button></div><SalesTable rows={recent} /></Card></>
}

function AddSale({ reload, notice }) { async function save(form) { try { await request('/sales', { method: 'POST', body: JSON.stringify(form) }); notice({ text: 'Sale saved successfully.' }); await reload() } catch (e) { notice({ type: 'error', text: e.message }); throw e } } return <><PageHead eyebrow="Sales desk" title="Add a new sale" /><Card className="form-card"><SaleForm onSave={save} /></Card></> }

function SalesTable({ rows, actions }) {
  if (!rows.length) return <Empty icon={ReceiptText} title="No transactions found" />
  return <div className="table-wrap"><table><thead><tr><th>ID</th><th>Customer</th><th>Date</th><th>Item</th><th>Sale</th><th>Paid</th><th>Pending</th><th>Status</th>{actions && <th />}</tr></thead><tbody>{rows.map((x) => <tr key={x.id}><td className="mono">#{x.id}</td><td><strong>{x.customer_name}</strong><small>{x.customer_phone || 'No phone'}</small></td><td>{dateLabel(x.sale_date)}</td><td>{x.product_category}<small>{x.product_description || x.vendor || '—'}</small></td><td>{money(x.selling_price)}</td><td>{money(x.amount_paid)}</td><td className={Number(x.pending_amount) ? 'pending-text' : ''}>{money(x.pending_amount)}</td><td><Status paid={x.payment_received} delayed={x.delay_status} /></td>{actions && <td>{actions(x)}</td>}</tr>)}</tbody></table></div>
}

function Review({ sales, reload, notice }) {
  const [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [collect, setCollect] = useState(null)
  const rows = sales.filter((x) => `${x.customer_name} ${x.customer_phone} ${x.vendor} ${x.product_description} ${x.id}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || (status === 'pending' ? Number(x.pending_amount) > 0 : Number(x.pending_amount) <= 0)))
  async function exportExcel() {
    const columns = [['ID','id'],['Customer','customer_name'],['Phone','customer_phone'],['Sale date','sale_date'],['Vendor','vendor'],['Category','product_category'],['Description','product_description'],['Buying price','buying_price'],['Selling price','selling_price'],['Amount paid','amount_paid'],['Pending amount','pending_amount'],['Payment method','payment_method'],['Notes','notes']]
    const header = columns.map(([value]) => ({ value, fontWeight: 'bold', color: '#ffffff', backgroundColor: '#2563eb' }))
    const body = rows.map((row) => columns.map(([, key]) => ({ value: row[key] ?? '', type: typeof row[key] === 'number' ? Number : String })))
    await writeXlsxFile([header, ...body], { fileName: `boutique-accounts-${today()}.xlsx`, sheet: 'Accounts' })
  }
  async function payment(data) { try { await request(`/sales/${collect.id}/payment`, { method: 'POST', body: JSON.stringify(data) }); notice({ text: 'Payment recorded.' }); setCollect(null); reload() } catch (e) { notice({ type: 'error', text: e.message }) } }
  return <><PageHead eyebrow="Accounts" title="Review transactions" action={<Button variant="secondary" icon={CloudDownload} onClick={exportExcel}>Export Excel</Button>} /><Card className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Search customer, phone, vendor or ID…" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="segmented">{['all','pending','paid'].map((x) => <button className={status === x ? 'active' : ''} onClick={() => setStatus(x)} key={x}>{x}</button>)}</div><span>{rows.length} records</span></Card><Card className="table-card"><SalesTable rows={rows} actions={(x) => Number(x.pending_amount) > 0 && <Button variant="tiny" onClick={() => setCollect(x)}>Collect</Button>} /></Card>{collect && <PaymentModal row={collect} close={() => setCollect(null)} save={payment} />}</>
}
function PaymentModal({ row, close, save }) { const [form, setForm] = useState({ amount: row.pending_amount, date: today(), method: 'UPI', received_by: 'Admin' }); return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={close}><X /></button><span className="eyebrow">Collect payment</span><h2>{row.customer_name}</h2><p>Pending balance: <strong>{money(row.pending_amount)}</strong></p><div className="form-grid two"><Field label="Amount" type="number" max={row.pending_amount} value={form.amount} onChange={(e) => setForm({...form, amount:e.target.value})}/><Field label="Date" type="date" value={form.date} onChange={(e) => setForm({...form, date:e.target.value})}/><Field label="Method" as="select" value={form.method} onChange={(e) => setForm({...form, method:e.target.value})}>{PAYMENT_METHODS.slice(0,4).map(x=><option key={x}>{x}</option>)}</Field><Field label="Received by" value={form.received_by} onChange={(e) => setForm({...form, received_by:e.target.value})}/></div><Button onClick={() => save(form)} icon={CircleDollarSign}>Record collection</Button></div></div> }

function UpdateSale({ sales, reload, notice }) {
  const [id, setId] = useState(sales[0]?.id || ''), row = sales.find((x) => Number(x.id) === Number(id))
  async function save(form) { try { await request(`/sales/${id}`, { method: 'PUT', body: JSON.stringify(form) }); notice({ text: `Transaction #${id} updated.` }); reload() } catch (e) { notice({ type: 'error', text: e.message }) } }
  async function del() { if (!confirm(`Delete transaction #${id}?`)) return; await request(`/sales/${id}`, { method: 'DELETE' }); notice({ text: 'Transaction deleted.' }); reload() }
  return <><PageHead eyebrow="Transaction editor" title="Update a sale" /><Card className="selector-card"><Field label="Choose transaction" as="select" value={id} onChange={(e) => setId(e.target.value)}>{sales.map((x) => <option value={x.id} key={x.id}>#{x.id} · {x.customer_name} · {dateLabel(x.sale_date)} · {money(x.selling_price)}</option>)}</Field></Card>{row ? <Card className="form-card"><SaleForm key={row.id} initial={{...row}} onSave={save} submitLabel="Save changes" /><Button className="danger-zone" variant="danger" icon={Trash2} onClick={del}>Delete transaction</Button></Card> : <Empty title="No transaction selected" />}</>
}

function Customers({ sales }) {
  const [q, setQ] = useState('')
  const customers = useMemo(() => { const map = {}; sales.forEach((x) => { const k=x.customer_name; map[k] ||= { name:k, phone:x.customer_phone, visits:0, spent:0, pending:0, last:x.sale_date }; const a=map[k]; a.visits++; a.spent+=Number(x.selling_price||0); a.pending+=Number(x.pending_amount||0); if(String(x.sale_date)>String(a.last)) a.last=x.sale_date }); return Object.values(map).sort((a,b)=>b.spent-a.spent) }, [sales])
  const rows = customers.filter((x) => `${x.name} ${x.phone}`.toLowerCase().includes(q.toLowerCase()))
  return <><PageHead eyebrow="Relationships" title="Customer directory" /><Card className="toolbar"><div className="search-box"><Search/><input placeholder="Find a customer…" value={q} onChange={(e)=>setQ(e.target.value)}/></div><span>{rows.length} customers</span></Card><div className="people-grid">{rows.map((x,i)=><Card className="person-card" key={x.name}><div className="avatar" style={{background:COLORS[i%COLORS.length]}}>{x.name[0]}</div><div className="person-head"><h3>{x.name}</h3><p>{x.phone||'No phone number'}</p></div><div className="person-stats"><div><span>Total spent</span><strong>{money(x.spent)}</strong></div><div><span>Transactions</span><strong>{x.visits}</strong></div><div><span>Pending</span><strong className={x.pending?'pending-text':''}>{money(x.pending)}</strong></div><div><span>Last visit</span><strong>{dateLabel(x.last)}</strong></div></div></Card>)}</div>{!rows.length&&<Empty icon={UsersRound} title="No customers found"/>}</>
}

function Vendors({ sales, inventory }) { const map={}; [...sales,...inventory].forEach((x)=>{if(!x.vendor)return; map[x.vendor]||={name:x.vendor,sales:0,stock:0,cost:0}; if(x.customer_name){map[x.vendor].sales++;map[x.vendor].cost+=Number(x.buying_price||0)}else map[x.vendor].stock+=Number(x.quantity||0)}); const rows=Object.values(map); return <><PageHead eyebrow="Supply network" title="Vendor directory" /><div className="people-grid">{rows.map((x,i)=><Card className="person-card" key={x.name}><div className="avatar square" style={{background:COLORS[(i+2)%COLORS.length]}}><ShoppingBag/></div><div className="person-head"><h3>{x.name}</h3><p>Active supplier</p></div><div className="person-stats"><div><span>Sale records</span><strong>{x.sales}</strong></div><div><span>Stock units</span><strong>{x.stock}</strong></div><div><span>Purchase value</span><strong>{money(x.cost)}</strong></div></div></Card>)}</div>{!rows.length&&<Empty icon={ShoppingBag} title="No vendors yet" copy="Vendor names from sales and inventory will appear here."/>}</> }

function Analytics({ sales }) {
  const [tab,setTab]=useState('trends'), m=calcMetrics(sales), monthly=monthlyData(sales)
  const grouped=(key)=>Object.values(sales.reduce((map,x)=>{const name=x[key]||'Other';map[name]||={name,value:0,count:0};map[name].value+=Number(x.selling_price||0);map[name].count++;return map},{})).sort((a,b)=>b.value-a.value)
  const data=tab==='categories'?grouped('product_category'):tab==='payments'?grouped('payment_method'):grouped('customer_name').slice(0,10)
  return <><PageHead eyebrow="Business intelligence" title="Analytics" /><div className="metrics-grid compact"><Metric label="Average order" value={money(m.count?m.revenue/m.count:0)} icon={ReceiptText}/><Metric label="Gross margin" value={`${m.revenue?(m.profit/m.revenue*100).toFixed(1):0}%`} icon={TrendingUp} tone="green"/><Metric label="Collection rate" value={`${m.revenue?((m.revenue-m.pending)/m.revenue*100).toFixed(1):0}%`} icon={WalletCards} tone="amber"/></div><div className="tabs">{['trends','customers','categories','payments'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><Card className="chart-card analytics-chart">{tab==='trends'?<><div className="card-title"><div><h2>Sales performance</h2><p>Monthly revenue and gross profit</p></div></div><ResponsiveContainer width="100%" height={380}><LineChart data={monthly}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`₹${v/1000}k`}/><Tooltip formatter={money}/><Legend/><Line type="monotone" dataKey="revenue" stroke="#2563eb" strokeWidth={3}/><Line type="monotone" dataKey="profit" stroke="#059669" strokeWidth={3}/></LineChart></ResponsiveContainer></>:<><div className="card-title"><div><h2>{tab[0].toUpperCase()+tab.slice(1)} breakdown</h2><p>Revenue contribution</p></div></div><div className="split-chart"><ResponsiveContainer width="55%" height={380}><BarChart data={data} layout="vertical"><CartesianGrid horizontal={false} stroke="var(--chart-grid)"/><XAxis type="number" tickFormatter={v=>`₹${v/1000}k`}/><YAxis dataKey="name" type="category" width={120}/><Tooltip formatter={money}/><Bar dataKey="value" fill="#2563eb" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer><ResponsiveContainer width="45%" height={380}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={65} outerRadius={110}>{data.map((_,i)=><Cell fill={COLORS[i%COLORS.length]} key={i}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer></div></>}</Card></>
}

function Reminders({ sales, reload, notice }) { const [tab,setTab]=useState('overdue'); const rows=sales.filter(x=>{const age=differenceInDays(new Date(),new Date(x.sale_date)); if(tab==='overdue')return Number(x.pending_amount)>0&&age>=30;if(tab==='flagged')return x.delay_status;if(tab==='high')return Number(x.pending_amount)>=5000;return Number(x.pending_amount)>0&&age<30}).sort((a,b)=>Number(b.pending_amount)-Number(a.pending_amount)); return <><PageHead eyebrow="Follow-up centre" title="Reminders & alerts" /><div className="tabs">{[['overdue','Overdue 30d+'],['flagged','Flagged'],['high','High value'],['upcoming','Upcoming']].map(([id,l])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{l}</button>)}</div><Card className="table-card"><SalesTable rows={rows}/></Card></> }

function Billing({ sales, notice }) {
  const names = [...new Set(sales.map((x) => x.customer_name).filter(Boolean))].sort((a, b) => a.localeCompare(b))
  const [customer, setCustomer] = useState(''), [scope, setScope] = useState('All Transactions'), [limit, setLimit] = useState(5)
  const [billDate, setBillDate] = useState(today()), [history, setHistory] = useState([]), [historySearch, setHistorySearch] = useState('')
  const [selectedBill, setSelectedBill] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { if (!customer && names.length) setCustomer(names[0]) }, [customer, names])
  const loadHistory = useCallback(() => request('/bills').then((rows) => { const sorted = rows.sort((a,b)=>String(b.generated_at).localeCompare(String(a.generated_at))); setHistory(sorted); if (!selectedBill && sorted.length) setSelectedBill(sorted[0].bill_id) }).catch((e) => notice({type:'error',text:e.message})), [notice, selectedBill])
  useEffect(() => { loadHistory() }, [])
  let rows = sales.filter((x) => x.customer_name === customer)
  if (scope === 'Pending Transactions') rows = rows.filter((x) => Number(x.pending_amount) > 0)
  if (scope === 'Last Transactions') rows = [...rows].sort((a,b)=>String(b.sale_date).localeCompare(String(a.sale_date))||Number(b.id)-Number(a.id)).slice(0, limit)
  rows = [...rows].sort((a,b)=>String(a.sale_date).localeCompare(String(b.sale_date))||Number(a.id)-Number(b.id))
  const totals = calcMetrics(rows), selectedDoc = history.find((x) => x.bill_id === selectedBill)
  const shownHistory = history.filter((x) => `${x.bill_id} ${x.customer_name} ${x.customer_phone}`.toLowerCase().includes(historySearch.toLowerCase()))
  async function generate() {
    if (!customer || !rows.length) return
    setBusy(true)
    try {
      const token = localStorage.getItem('boutique_token')
      const response = await fetch('/api/bills/generate', { method:'POST', headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}, body:JSON.stringify({customer_name:customer,bill_scope:scope,bill_limit:limit,bill_date:billDate}) })
      if (!response.ok) { const error = await response.json().catch(()=>({})); throw new Error(error.error || 'Could not generate the bill.') }
      const blob = await response.blob(), disposition = response.headers.get('Content-Disposition') || '', id = response.headers.get('X-Bill-ID') || 'bill'
      const filename = disposition.match(/filename="([^"]+)"/)?.[1] || `${id}.pdf`, url = URL.createObjectURL(blob), link = document.createElement('a')
      link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url)
      notice({text:`Bill ${id} generated, saved to history, and downloaded.`}); await loadHistory()
    } catch (e) { notice({type:'error',text:e.message}) } finally { setBusy(false) }
  }
  return <><PageHead eyebrow="Customer PDF statement" title="Generate a bill" />
    <Card className="bill-controls"><div className="form-grid four"><Field label="Customer" as="select" value={customer} onChange={(e)=>setCustomer(e.target.value)}>{names.map((name)=>{const all=sales.filter(x=>x.customer_name===name),m=calcMetrics(all);return <option value={name} key={name}>{name} — Pending {money(m.pending)} / Total {money(m.revenue)}</option>})}</Field><Field label="Bill type" as="select" value={scope} onChange={(e)=>setScope(e.target.value)}><option>All Transactions</option><option>Last Transactions</option><option>Pending Transactions</option></Field><Field label="Last transactions" type="number" min="1" max="100" disabled={scope!=='Last Transactions'} value={limit} onChange={(e)=>setLimit(Number(e.target.value))}/><Field label="Bill date" type="date" value={billDate} onChange={(e)=>setBillDate(e.target.value)}/></div></Card>
    <div className="metrics-grid"><Metric label="Purchases" value={rows.length} icon={ReceiptText}/><Metric label="Total bill" value={money(totals.revenue)} icon={IndianRupee}/><Metric label="Paid" value={money(totals.revenue-totals.pending)} icon={CircleDollarSign} tone="green"/><Metric label="Pending" value={money(totals.pending)} icon={WalletCards} tone="amber"/></div>
    <Card className="invoice-preview"><div className="invoice-head"><div><span className="eyebrow">{scope==='Last Transactions'?`Last ${limit} transactions`:scope}</span><h2>Shree Krishna Boutique</h2><p>{customer||'Select a customer'}</p></div><div><span>Total due</span><strong>{money(totals.pending)}</strong></div></div><SalesTable rows={rows}/><div className="invoice-total"><span>Total billed <strong>{money(totals.revenue)}</strong></span><span>Paid <strong>{money(totals.revenue-totals.pending)}</strong></span><span>Balance <strong>{money(totals.pending)}</strong></span></div><Button icon={FileText} onClick={generate} disabled={!rows.length||busy}>{busy?'Generating with Python…':'Generate bill PDF'}</Button></Card>
    <div className="section-divider"><span>Bill history</span></div><Card className="table-card"><div className="card-title"><div><h2>Generated bills</h2><p>Permanent bill IDs and transaction snapshots</p></div><div className="search-box"><Search/><input placeholder="Search bill, customer or phone…" value={historySearch} onChange={(e)=>setHistorySearch(e.target.value)}/></div></div>{shownHistory.length?<div className="table-wrap"><table><thead><tr><th>Bill ID</th><th>Customer</th><th>Type</th><th>Date</th><th>Purchases</th><th>Total</th><th>Paid</th><th>Pending</th></tr></thead><tbody>{shownHistory.map((x)=><tr key={x.bill_id} className={selectedBill===x.bill_id?'selected-row':''} onClick={()=>setSelectedBill(x.bill_id)}><td className="mono">{x.bill_id}</td><td><strong>{x.customer_name}</strong><small>{x.customer_phone||'No phone'}</small></td><td>{x.bill_scope_label||x.bill_scope}</td><td>{dateLabel(x.bill_date)}</td><td>{x.purchase_count}</td><td>{money(x.total_bill)}</td><td>{money(x.total_paid)}</td><td className={Number(x.total_pending)?'pending-text':''}>{money(x.total_pending)}</td></tr>)}</tbody></table></div>:<Empty icon={ReceiptText} title="No generated bills found"/>}</Card>
    {selectedDoc?.items?.length>0&&<Card className="table-card bill-detail"><div className="card-title"><div><h2>{selectedDoc.bill_id}</h2><p>{selectedDoc.customer_name} · Generated {dateLabel(selectedDoc.generated_at)} by {selectedDoc.generated_by}</p></div><span className={`badge ${Number(selectedDoc.total_pending)?'amber':'green'}`}>{Number(selectedDoc.total_pending)?'Pending':'Paid'}</span></div><div className="table-wrap"><table><thead><tr><th>Sale ID</th><th>Date</th><th>Category</th><th>Description</th><th>Bill</th><th>Paid</th><th>Pending</th><th>Status</th></tr></thead><tbody>{selectedDoc.items.map((x)=><tr key={x.sale_id}><td className="mono">#{x.sale_id}</td><td>{dateLabel(x.sale_date)}</td><td>{x.category}</td><td>{x.description||'—'}</td><td>{money(x.bill_amount)}</td><td>{money(x.paid_amount)}</td><td>{money(x.pending_amount)}</td><td><span className={`badge ${x.status?.startsWith('PAID')?'green':'amber'}`}>{x.status}</span></td></tr>)}</tbody></table></div></Card>}
  </>
}

function Inventory({ inventory, reload, notice }) {
  const blank={item:'',vendor:'',category:'Sarees',quantity:'',reorder_level:'',cost_price:'',selling_price:''}, [form,setForm]=useState(blank)
  async function save(e){e.preventDefault();try{await request('/inventory',{method:'POST',body:JSON.stringify(form)});setForm(blank);notice({text:'Inventory updated.'});reload()}catch(e){notice({type:'error',text:e.message})}}
  async function del(id){await request(`/inventory/${id}`,{method:'DELETE'});reload()}
  return <><PageHead eyebrow="Stock control" title="Inventory" /><div className="metrics-grid compact"><Metric label="Stock units" value={inventory.reduce((n,x)=>n+Number(x.quantity||0),0)} icon={Boxes}/><Metric label="Low stock" value={inventory.filter(x=>Number(x.quantity)<=Number(x.reorder_level)).length} icon={AlertTriangle} tone="amber"/><Metric label="Stock value" value={money(inventory.reduce((n,x)=>n+Number(x.quantity||0)*Number(x.cost_price||0),0))} icon={IndianRupee} tone="green"/></div><div className="two-column"><Card className="table-card"><div className="card-title"><div><h2>Current stock</h2><p>{inventory.length} tracked items</p></div></div>{inventory.length?<div className="table-wrap"><table><thead><tr><th>Item</th><th>Vendor</th><th>Category</th><th>Qty</th><th>Price</th><th/></tr></thead><tbody>{inventory.map(x=><tr key={x.id}><td><strong>{x.item}</strong></td><td>{x.vendor||'—'}</td><td>{x.category}</td><td><span className={`badge ${Number(x.quantity)<=Number(x.reorder_level)?'red':'green'}`}>{x.quantity}</span></td><td>{money(x.selling_price)}</td><td><button className="row-action danger" onClick={()=>del(x.id)}><Trash2/></button></td></tr>)}</tbody></table></div>:<Empty icon={Boxes}/>}</Card><Card className="form-card side-form"><div className="card-title"><div><h2>Add or update stock</h2><p>Enter an existing ID to update it</p></div></div><form onSubmit={save}><div className="form-grid two"><Field label="ID (optional)" value={form.id||''} onChange={e=>setForm({...form,id:e.target.value})}/><Field label="Item name" value={form.item} onChange={e=>setForm({...form,item:e.target.value})} required/><Field label="Vendor" value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/><Field label="Category" as="select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</Field><Field label="Quantity" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><Field label="Reorder at" type="number" value={form.reorder_level} onChange={e=>setForm({...form,reorder_level:e.target.value})}/><Field label="Cost price" type="number" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})}/><Field label="Selling price" type="number" value={form.selling_price} onChange={e=>setForm({...form,selling_price:e.target.value})}/></div><Button icon={PackagePlus}>Save stock</Button></form></Card></div></>
}

function passbookDate(value) { const parts=String(value||'').split('/'); return parts.length===3?`${parts[2]}-${parts[1]}-${parts[0]}`:today() }
function Passbook({ sales, reload, notice }) {
  const [files,setFiles]=useState([]),[passbooks,setPassbooks]=useState([]),[selectedIdx,setSelectedIdx]=useState(0),[nameFilter,setNameFilter]=useState('All Names'),[typeFilter,setTypeFilter]=useState('All'),[vendors,setVendors]=useState([]),[busy,setBusy]=useState(false),[selectedTxn,setSelectedTxn]=useState(0)
  const [sale,setSale]=useState({customer_name:'',customer_phone:'',sale_date:today(),product_category:'Sarees',vendor:'',quantity:1,product_description:'',buying_price:0,selling_price:0,amount_paid:0,payment_method:'UPI',notes:''})
  const loadVendors=useCallback(()=>request('/passbook/vendors').then(setVendors).catch(()=>{}),[])
  useEffect(()=>{loadVendors()},[loadVendors])
  async function parse(){setBusy(true);const body=new FormData();files.forEach((file)=>body.append('files',file));try{const data=await request('/passbook/parse',{method:'POST',body,timeout:90000});setPassbooks(data.passbooks||[]);setSelectedIdx(0);setNameFilter('All Names');setTypeFilter('All');notice({text:`${data.passbooks?.length||0} passbook PDF(s) parsed with the Python extractor.`})}catch(e){notice({type:'error',text:e.message})}finally{setBusy(false)}}
  const pb=passbooks[selectedIdx], allRows=pb?.transactions||[], names=[...new Set(allRows.map((x)=>x.Name).filter(Boolean))].sort((a,b)=>a.localeCompare(b)), vendorKeys=new Set(vendors.map((x)=>x.toLowerCase()))
  const filtered=allRows.filter((x)=>(nameFilter==='All Names'||(nameFilter==='Saved Vendors'?vendorKeys.has(String(x.Name).toLowerCase()):x.Name===nameFilter))&&(typeFilter==='All'||(typeFilter==='Credit'?Number(x.Credit)>0:Number(x.Debit)>0)))
  const currentTxn=filtered[selectedTxn]||filtered[0], totalCredit=filtered.reduce((n,x)=>n+Number(x.Credit||0),0),totalDebit=filtered.reduce((n,x)=>n+Number(x.Debit||0),0),lastBalance=filtered.length?Number(filtered[filtered.length-1].Balance||0):0
  useEffect(()=>{setSelectedTxn(0)},[nameFilter,typeFilter,selectedIdx])
  useEffect(()=>{if(!currentTxn)return;const txnAmount=Number(currentTxn.Debit||0)||Number(currentTxn.Credit||0);setSale((old)=>({...old,sale_date:passbookDate(currentTxn.Date),vendor:currentTxn.Name||'',product_description:currentTxn.Description||'',buying_price:txnAmount,selling_price:txnAmount,amount_paid:0,notes:`From passbook transaction: ${currentTxn.Description||''}`}))},[currentTxn?.Date,currentTxn?.Description,currentTxn?.Name,currentTxn?.Debit,currentTxn?.Credit])
  async function toggleVendor(){if(!nameFilter||['All Names','Saved Vendors'].includes(nameFilter))return;const saved=vendorKeys.has(nameFilter.toLowerCase());try{await request(`/passbook/vendors${saved?`/${encodeURIComponent(nameFilter)}`:''}`,{method:saved?'DELETE':'POST',...(saved?{}:{body:JSON.stringify({name:nameFilter})})});await loadVendors();notice({text:`${nameFilter} ${saved?'removed from':'saved as'} vendor.`})}catch(e){notice({type:'error',text:e.message})}}
  function downloadCsv(){const columns=['Date','Name','Description','Debit','Credit','Balance'],escape=(v)=>`"${String(v??'').replaceAll('"','""')}"`,csv=[columns.join(','),...filtered.map((row)=>columns.map((key)=>escape(row[key])).join(','))].join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),link=document.createElement('a');link.href=url;link.download=`passbook_${(nameFilter==='All Names'?pb.customer_name:nameFilter).replace(/\W+/g,'_').toLowerCase()}_${today()}.csv`;link.click();URL.revokeObjectURL(url)}
  async function saveSale(e){e.preventDefault();if(!currentTxn)return;try{await request('/sales',{method:'POST',body:JSON.stringify({...sale,passbook_source:{date:currentTxn.Date,name:currentTxn.Name,description:currentTxn.Description,debit:Number(currentTxn.Debit||0),credit:Number(currentTxn.Credit||0),balance:Number(currentTxn.Balance||0)}})});notice({text:`Sale added for ${sale.customer_name} from the passbook transaction.`});await reload()}catch(e){notice({type:'error',text:e.message})}}
  return <><PageHead eyebrow="PDF statement extractor" title="Passbook reader" />
    <Card className="upload-card"><span className="upload-icon"><Upload/></span><h2>Upload passbook PDFs</h2><p>The original Python table and text extraction logic reads account details, debit/credit rows, names, and balances.</p><input type="file" accept="application/pdf" multiple onChange={(e)=>setFiles([...e.target.files])}/><Button onClick={parse} disabled={!files.length||busy} icon={FileSearch}>{busy?'Reading with Python…':`Read ${files.length||''} passbook${files.length===1?'':'s'}`}</Button></Card>
    {pb&&<><Card className="passbook-account"><div className="card-title"><div><span className="eyebrow">Account details</span><h2>{pb.customer_name||pb.filename}</h2><p>{pb.bank} · {pb.statement_date||pb.statement_period}</p></div><span className="badge blue">{pb.filename}</span></div><div className="account-grid"><div><span>Account</span><strong>{pb.account_no_15||pb.account_no||'—'}</strong></div><div><span>IFSC</span><strong>{pb.ifsc||'—'}</strong></div><div><span>Branch</span><strong>{pb.branch||'—'}</strong></div><div><span>Account type</span><strong>{pb.account_type||'—'}</strong></div></div>{pb.address&&<p className="account-address">{pb.address}</p>}</Card>
      <Card className="passbook-filters"><div className="form-grid three"><Field label="Name filter" as="select" value={nameFilter} onChange={(e)=>setNameFilter(e.target.value)}><option>All Names</option><option>Saved Vendors</option>{names.map((x)=><option key={x}>{x}</option>)}</Field><Field label="Passbook" as="select" value={selectedIdx} onChange={(e)=>setSelectedIdx(Number(e.target.value))}>{passbooks.map((x,i)=><option value={i} key={`${x.filename}-${i}`}>{x.customer_name} — {x.statement_date||x.account_no_15||x.filename}</option>)}</Field><Field label="Type" as="select" value={typeFilter} onChange={(e)=>setTypeFilter(e.target.value)}><option>All</option><option>Credit</option><option>Debit</option></Field></div><div className="filter-actions"><Button variant="secondary" onClick={toggleVendor} disabled={['All Names','Saved Vendors'].includes(nameFilter)}>{vendorKeys.has(nameFilter.toLowerCase())?'Remove vendor':'Mark as vendor'}</Button><span>{vendors.length} saved vendors</span></div></Card>
      <div className="metrics-grid"><Metric label="Rows" value={filtered.length} icon={ClipboardList}/><Metric label="Credits" value={money(totalCredit)} icon={TrendingUp} tone="green"/><Metric label="Debits" value={money(totalDebit)} icon={WalletCards} tone="amber"/><Metric label="Last balance" value={money(lastBalance)} icon={IndianRupee}/></div>
      <Card className="table-card"><div className="card-title"><div><h2>Transactions</h2><p>{nameFilter} · {typeFilter}</p></div><Button variant="secondary" icon={CloudDownload} disabled={!filtered.length} onClick={downloadCsv}>Download filtered CSV</Button></div>{filtered.length?<div className="table-wrap passbook-table"><table><thead><tr><th>Date</th><th>Name</th><th>Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{filtered.map((x,i)=><tr key={`${x.Date}-${x.Description}-${i}`} className={selectedTxn===i?'selected-row':''} onClick={()=>setSelectedTxn(i)}><td>{x.Date}</td><td><strong>{x.Name}</strong></td><td>{x.Description}</td><td className={Number(x.Debit)?'pending-text':''}>{Number(x.Debit)?money(x.Debit):'—'}</td><td className={Number(x.Credit)?'credit-text':''}>{Number(x.Credit)?money(x.Credit):'—'}</td><td>{money(x.Balance)}</td></tr>)}</tbody></table></div>:<Empty icon={FileSearch} title="No transaction rows match this filter"/>}</Card>
      {currentTxn&&<Card className="passbook-sale"><div className="card-title"><div><h2>Add sale from transaction</h2><p>{currentTxn.Date} · {currentTxn.Name} · Debit {money(currentTxn.Debit)} · Credit {money(currentTxn.Credit)}</p></div><span className="badge blue">Selected row {selectedTxn+1}</span></div><Field label="Select transaction" as="select" value={selectedTxn} onChange={(e)=>setSelectedTxn(Number(e.target.value))}>{filtered.map((x,i)=><option value={i} key={i}>{x.Date} — {x.Name} — Debit {money(x.Debit)} — Credit {money(x.Credit)}</option>)}</Field><form onSubmit={saveSale}><div className="form-grid three"><Field label="Customer name *" value={sale.customer_name} onChange={(e)=>setSale({...sale,customer_name:e.target.value})} required/><Field label="Phone" value={sale.customer_phone} onChange={(e)=>setSale({...sale,customer_phone:e.target.value})}/><Field label="Sale date" type="date" value={sale.sale_date} onChange={(e)=>setSale({...sale,sale_date:e.target.value})}/><Field label="Category *" as="select" value={sale.product_category} onChange={(e)=>setSale({...sale,product_category:e.target.value})}>{CATEGORIES.map((x)=><option key={x}>{x}</option>)}</Field><Field label="Vendor *" value={sale.vendor} onChange={(e)=>setSale({...sale,vendor:e.target.value})} required/><Field label="Quantity" type="number" min="1" value={sale.quantity} onChange={(e)=>setSale({...sale,quantity:Number(e.target.value)})}/></div><Field label="Description" as="textarea" rows="2" value={sale.product_description} onChange={(e)=>setSale({...sale,product_description:e.target.value})}/><div className="form-grid four"><Field label="Buying price *" type="number" min="0.01" step="0.01" value={sale.buying_price} onChange={(e)=>setSale({...sale,buying_price:Number(e.target.value)})}/><Field label="Selling price *" type="number" min="0.01" step="0.01" value={sale.selling_price} onChange={(e)=>setSale({...sale,selling_price:Number(e.target.value)})}/><Field label="Amount paid" type="number" min="0" step="0.01" value={sale.amount_paid} onChange={(e)=>setSale({...sale,amount_paid:Number(e.target.value)})}/><Field label="Payment method" as="select" value={sale.payment_method} onChange={(e)=>setSale({...sale,payment_method:e.target.value})}>{PAYMENT_METHODS.map((x)=><option key={x}>{x}</option>)}</Field></div><div className="sale-summary"><span>Pending <strong>{money(Math.max(Number(sale.selling_price)-Number(sale.amount_paid),0))}</strong></span><span>Profit <strong>{money((Number(sale.selling_price)-Number(sale.buying_price))*Number(sale.quantity||1))}</strong></span><span>Total value <strong>{money(Number(sale.selling_price)*Number(sale.quantity||1))}</strong></span></div><Field label="Notes" as="textarea" rows="2" value={sale.notes} onChange={(e)=>setSale({...sale,notes:e.target.value})}/><Button icon={Plus}>Save sale</Button></form></Card>}
      <details className="details-card"><summary>Saved vendors ({vendors.length})</summary>{vendors.length?<div className="vendor-chips">{vendors.map((x)=><span key={x}>{x}<button onClick={async()=>{await request(`/passbook/vendors/${encodeURIComponent(x)}`,{method:'DELETE'});loadVendors()}}><X/></button></span>)}</div>:<p>No saved vendors yet.</p>}</details><details className="details-card"><summary>All names found ({names.length})</summary><div className="name-counts">{names.map((name)=><span key={name}>{name}<strong>{allRows.filter((x)=>x.Name===name).length}</strong></span>)}</div></details>
    </>}
  </>
}

function Notes({ notes,reload,notice }) { const [form,setForm]=useState({work_date:today(),note:''});async function save(e){e.preventDefault();try{await request('/notes',{method:'POST',body:JSON.stringify(form)});setForm({...form,note:''});notice({text:'Work note saved.'});reload()}catch(e){notice({type:'error',text:e.message})}}async function del(id){await request(`/notes/${id}`,{method:'DELETE'});reload()}return <><PageHead eyebrow="Manual activity log" title="Work notes" /><Card className="note-entry"><form onSubmit={save}><Field label="Date" type="date" value={form.work_date} onChange={e=>setForm({...form,work_date:e.target.value})}/><Field label="What did you work on?" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Updated accounts, checked passbook…"/><Button icon={NotebookPen}>Save note</Button></form></Card><div className="timeline">{notes.map(x=><div className="timeline-row" key={x.id}><div className="timeline-dot"/><Card><div><span>{dateLabel(x.work_date)}</span><small>Saved by {x.created_by} · {dateLabel(x.created_at)}</small></div><p>{x.note}</p><button className="row-action danger" onClick={()=>del(x.id)}><Trash2/></button></Card></div>)}</div>{!notes.length&&<Empty icon={NotebookPen} title="No work notes yet"/>}</> }

function AI(){const quick=['Summarize today’s business status and what needs attention.','List customers with the most pending amount and suggest follow-up priority.','Find sales or vendors that look unusual.','Draft polite payment reminder messages for pending customers.','Review inventory and suggest restock actions.'];const[q,setQ]=useState(quick[0]),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function ask(){setBusy(true);setError('');try{const r=await request('/ai',{method:'POST',body:JSON.stringify({question:q})});setAnswer(r.answer)}catch(e){setError(e.message)}finally{setBusy(false)}}return <><PageHead eyebrow="Data-aware assistant" title="AI assistant" /><div className="ai-layout"><Card className="ai-compose"><span className="ai-orb"><Bot/></span><h2>What would you like to know?</h2><p>The assistant receives a protected summary of your sales, inventory and work notes.</p><Field label="Quick question" as="select" value={q} onChange={e=>setQ(e.target.value)}>{quick.map(x=><option key={x}>{x}</option>)}<option>Custom question</option></Field><Field label="Question" as="textarea" rows="5" value={q} onChange={e=>setQ(e.target.value)}/><Button onClick={ask} disabled={busy||!q} icon={Sparkles}>{busy?'Thinking…':'Ask assistant'}</Button>{error&&<p className="form-error">{error}</p>}</Card><Card className="ai-answer">{answer?<><span className="eyebrow">Assistant response</span><div className="answer-text">{answer}</div></>:<Empty icon={Bot} title="Your answer will appear here" copy="Ask about accounts, collections, inventory, vendors or daily priorities."/>}</Card></div></>}

function Technical({sales,inventory,notes}){const[health,setHealth]=useState(null);useEffect(()=>{request('/health').then(setHealth)},[]);const collections=[['Sales',sales.length],['Inventory',inventory.length],['Work notes',notes.length]];return <><PageHead eyebrow="System administration" title="Technical overview" /><div className="metrics-grid compact"><Metric label="API status" value={health?.ok?'Online':'Checking…'} icon={Activity} tone="green"/><Metric label="Database" value={health?.database||'—'} icon={Database}/><Metric label="App version" value="3.0 React" icon={Sparkles} tone="violet"/></div><Card className="technical-card"><div className="card-title"><div><h2>Data collections</h2><p>Live records available to this workspace</p></div></div>{collections.map(([n,v])=><div className="collection-row" key={n}><span><Database/>{n}</span><strong>{v} documents</strong></div>)}</Card><Card className="env-help"><AlertTriangle/><div><h3>Environment configuration</h3><p>MongoDB, authentication, JWT and AI provider keys are server-only. Copy <code>.env.example</code> to <code>.env</code> and fill in production values before deployment.</p></div></Card></>}

function Security(){const[devices,setDevices]=useState([]);const load=()=>request('/devices').then(setDevices);useEffect(load,[]);async function toggle(x){await request(`/devices/${x.id}`,{method:'PATCH',body:JSON.stringify({active:!x.active})});load()}return <><PageHead eyebrow="Access control" title="Security & devices" /><Card className="security-banner"><span><ShieldCheck/></span><div><h2>Authenticated device sessions</h2><p>Review and revoke browsers that have accessed the admin workspace.</p></div></Card><Card className="table-card">{devices.length?<div className="table-wrap"><table><thead><tr><th>User</th><th>Method</th><th>Last login</th><th>Status</th><th/></tr></thead><tbody>{devices.map(x=><tr key={x.id}><td><strong>{x.username}</strong><small>{x.user_agent?.slice(0,55)}</small></td><td>{x.login_method}</td><td>{dateLabel(x.last_login_at)}</td><td><span className={`badge ${x.active?'green':'red'}`}>{x.active?'Active':'Revoked'}</span></td><td><Button variant="tiny" onClick={()=>toggle(x)}>{x.active?'Revoke':'Restore'}</Button></td></tr>)}</tbody></table></div>:<Empty icon={ShieldCheck} title="No devices recorded"/>}</Card></>}

function Backup({reload,notice}){const[file,setFile]=useState(null);async function download(){const token=localStorage.getItem('boutique_token');const r=await fetch('/api/backup',{headers:{Authorization:`Bearer ${token}`}});const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`boutique-backup-${today()}.json`;a.click();URL.revokeObjectURL(url);notice({text:'Backup downloaded.'})}async function restore(){if(!file||!confirm('Insert all records from this backup? Duplicates may result.'))return;try{const data=JSON.parse(await file.text());const r=await request('/restore',{method:'POST',body:JSON.stringify(data)});notice({text:`Restore complete: ${r.inserted} records inserted.`});reload()}catch(e){notice({type:'error',text:e.message})}}return <><PageHead eyebrow="Data resilience" title="Backup & restore" /><div className="backup-grid"><Card className="backup-card"><span className="backup-icon blue"><CloudDownload/></span><h2>Download checkpoint</h2><p>Export sales, inventory, work notes, bills, devices and settings in one JSON checkpoint.</p><Button icon={CloudDownload} onClick={download}>Download backup</Button></Card><Card className="backup-card"><span className="backup-icon green"><Upload/></span><h2>Restore checkpoint</h2><p>Insert records from a previously downloaded application checkpoint.</p><input type="file" accept="application/json" onChange={e=>setFile(e.target.files[0])}/><Button variant="secondary" icon={ArchiveRestore} disabled={!file} onClick={restore}>Restore backup</Button></Card></div><Card className="env-help danger-help"><AlertTriangle/><div><h3>Restore is additive</h3><p>Existing records are preserved. Restoring the same checkpoint more than once can create duplicates.</p></div></Card></>}

export default function App() {
  const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('boutique_user')) } catch { return null } })
  function logout() { localStorage.removeItem('boutique_token'); localStorage.removeItem('boutique_user'); setUser(null) }
  return user ? <Shell user={user} logout={logout} /> : <PublicHome onLogin={setUser} />
}
